<?php

namespace Multiple\Backend\Models;

class Comments extends  ModelBase
{
    public $idx;
    public $board_id;
    public $board_idx;
    public $memo;
    public $member;
    public $created;
    public function initialize()
    {
        $this->setschema("tj_board");
    }
    public function setSource($source)
    {
        parent::setSource($source); // TODO: Change the autogenerated stub
    }
    public function getSource()
    {
        return parent::getSource(); // TODO: Change the autogenerated stub
    }
    public function beforeValidationOnCreate()
    {
        $this->created = date('Y-m-d H:i:s');
    }
}