<?php

namespace Multiple\Backend\Models;

use Phalcon\Validation;
use Phalcon\Validation\Validator\PresenceOf as PresenceOf;

class SetupBoard extends ModelBase
{
    public $idx;
    public $id;
    public $name;
    public $skin;
    public $file;
    public $reply;
    public $comment;
    public $created;
    public function initialize()
    {
        $this->setschema("tj_board");
        $this->allowEmptyStringValues(['id', 'name', 'skin']);
        //$this->skipAttributes(['idx']);
    }
    public function setSource($source)
    {
        parent::setSource("setup_".$source); // TODO: Change the autogenerated stub
    }
    public function getSource()
    {
        return parent::getSource(); // TODO: Change the autogenerated stub
    }
    public function beforeValidationOnCreate()
    {
        $this->created = date('Y-m-d H:i:s');
    }
    public function validation()
    {
        $validator = new Validation();
        $validator->add(['id','name'], new PresenceOf([
            'message' => [
                'id' => 'id을 입력하세요.',                
                'name' => 'title을 입력하세요.',
                'skin' => 'skin을 선택하세요.'
            ],
        ]));
        return $this->validate($validator);
    }
}